#!/bin/bash

set -e

USER=`whoami`
HOST=`hostname -s`
DOMAIN=`hostname -d`

SERVERS=1
CONF_DIR="/usr/local/zookeeper/conf"
DATA_DIR="/data/zookeeper/data"
DATA_LOG_DIR="/data/zookeeper/log"
LOG_DIR="/var/log/zookeeper"
SERVER_PORT=2888
CLIENT_PORT=2181
LEADER_ELECTION_PORT=3888
INIT_LIMIT=10
TICK_TIME=2000
SYNC_LIMIT=5
HEAP=1G
MAX_CLIENT_CNXNS=100
SNAP_RETAIN_COUNT=3
PURGE_INTERVAL=0
LOG_LEVEL="INFO"

function create_config() {
    rm -f $CONFIG_FILE

    echo "# The number of milliseconds of each tick" >> $CONFIG_FILE
    echo "tickTime=$TICK_TIME" >> $CONFIG_FILE

    echo "# The number of ticks that the initial " >>$CONFIG_FILE
    echo "# synchronization phase can take" >> $CONFIG_FILE
    echo "initLimit=$INIT_LIMIT" >> $CONFIG_FILE

    echo "# The number of ticks that can pass between " >> $CONFIG_FILE
    echo "# sending a request and getting an acknowledgement" >> $CONFIG_FILE
    echo "syncLimit=$SYNC_LIMIT" >> $CONFIG_FILE

    echo "# the directory where the snapshot is stored." >> $CONFIG_FILE
    echo "# do not use /tmp for storage, /tmp here is just" >> $CONFIG_FILE
    echo "# example sakes." >> $CONFIG_FILE
    echo "dataDir=$DATA_DIR" >> $CONFIG_FILE
    echo "dataLogDir=$DATA_LOG_DIR" >> $CONFIG_FILE

    echo "# the port at which the clients will connect" >> $CONFIG_FILE
    echo "clientPort=$CLIENT_PORT" >> $CONFIG_FILE

    echo "# the maximum number of client connections." >> $CONFIG_FILE
    echo "# increase this if you need to handle more clients" >> $CONFIG_FILE
    echo "maxClientCnxns=$MAX_CLIENT_CNXNS" >> $CONFIG_FILE

    echo "#" >> $CONFIG_FILE
    echo "# Be sure to read the maintenance section of the " >> $CONFIG_FILE
    echo "# administrator guide before turning on autopurge." >> $CONFIG_FILE
    echo "#" >> $CONFIG_FILE
    echo "# http://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_maintenance" >> $CONFIG_FILE
    echo "#" >> $CONFIG_FILE
    echo "# The number of snapshots to retain in dataDir" >> $CONFIG_FILE
    echo "autopurge.snapRetainCount=$SNAP_RETAIN_COUNT" >> $CONFIG_FILE
    echo "# Purge task interval in hours" >> $CONFIG_FILE
    echo "# Set to \"0\" to disable auto purge feature" >> $CONFIG_FILE
    echo "autopurge.purgeInterval=$PURGE_INTERVAL" >> $CONFIG_FILE

    echo "minSessionTimeout=$MIN_SESSION_TIMEOUT" >> $CONFIG_FILE
    echo "maxSessionTimeout=$MAX_SESSION_TIMEOUT" >> $CONFIG_FILE

    echo "" >> $CONFIG_FILE

    echo "leaderServes=no" >> $CONFIG_FILE

    echo "" >> $CONFIG_FILE

    if [ $SERVERS -gt 1 ]; then
        print_servers >> $CONFIG_FILE
    fi

    cat $CONFIG_FILE >&2
}

function create_data_dirs() {
    if [ ! -d $DATA_DIR  ]; then
        mkdir -p $DATA_DIR
        chown -R $USER:$USER $DATA_DIR
    fi

    if [ ! -d $DATA_LOG_DIR  ]; then
        mkdir -p $DATA_LOG_DIR
        chown -R $USER:USER $DATA_LOG_DIR
    fi

    if [ ! -d $LOG_DIR  ]; then
        mkdir -p $LOG_DIR
        chown -R $USER:$USER $LOG_DIR
    fi
    if [ ! -f $MYID_FILE ] && [ $SERVERS -gt 1 ]; then
        echo $MY_ID >> $MYID_FILE
    fi
}

function print_servers() {
    for (( i=1; i<=$SERVERS; i++ ))
    do
        echo "server.$i=$NAME-$((i-1)).$DOMAIN:$SERVER_PORT:$LEADER_ELECTION_PORT"
    done
}

function create_jvm_props() {
    rm -f $JAVA_ENV_FILE
    echo "ZOO_LOG_DIR=$LOG_DIR" >> $JAVA_ENV_FILE
    echo "JVMFLAGS=\"-Xmx$HEAP -Xms$HEAP\"" >> $JAVA_ENV_FILE
}

function create_log_props() {
    ls -la $LOGGER_PROPS_FILE
}

function start() {
    exec /usr/local/zookeeper/bin/zkServer.sh start-foreground
}

function usage() {
echo "\
Usage: zookeeper [OPTIONS]
Starts a ZooKeeper server based on the supplied options.
    --servers               The number of servers in the ensemble. The default 
                            value is "$SERVERS".

    --conf_dir              The directoyr where the ZooKeeper process will store its
                            configuration. The default is "$CONF_DIR".

    --data_dir              The directory where the ZooKeeper process will store its
                            snapshots. The default is "$DATA_DIR".

    --data_log_dir          The directory where the ZooKeeper process will store its 
                            write ahead log. The default is "$DATA_LOG_DIR".

    --server_port           The port on which the ZooKeeper process will listen for 
                            requests from other servers in the ensemble. The 
                            default is "$SERVER_PORT". 

    --client_port           The port on which the ZooKeeper process will listen for 
                            client requests. The default is "$CLIENT_PORT".

    --leader_election_port  The port on which the ZooKeeper process will perform 
                            leader election. The default is "$LEADER_ELECTION_PORT".

    --init_limit            The number of Ticks that an ensemble member is allowed 
                            to perform leader election. The default is "$INIT_LIMIT".

    --tick_time             The length of a ZooKeeper tick in ms. The default is "$TICK_TIME".

    --sync_limit            The maximum session timeout that the ensemble will 
                            allows a client to request. The default is "$SYNC_LIMIT".

    --heap                  The maximum amount of heap to use. The format is the 
                            same as that used for the Xmx and Xms parameters to the 
                            JVM. e.g. --heap=2G. The default is "$HEAP".

    --max_client_cnxns      The maximum number of client connections that the 
                            ZooKeeper process will accept simultaneously. The 
                            default is "$MAX_CLIENT_CNXNS".

    --snap_retain_count     The maximum number of snapshots the ZooKeeper process 
                            will retain if purge_interval is greater than 0. The 
                            default is "$SNAP_RETAIN_COUNT".

    --purge_interval        The number of hours the ZooKeeper process will wait 
                            between purging its old snapshots. If set to 0 old 
                            snapshots will never be purged. The default is "$PURGE_INTERVAL".

    --max_session_timeout   The maximum time in milliseconds for a client session 
                            timeout. The default value is 2 * tick time.

    --min_session_timeout   The minimum time in milliseconds for a client session 
                            timeout. The default value is 20 * tick time.

    --log_level             The log level for the zookeeeper server. Either FATAL,
                            ERROR, WARN, INFO, DEBUG. The default is "$LOG_LEVEL".
"
}

optspec=":hv-:"
while getopts "$optspec" optchar; do
    case "${optchar}" in
        -)
            case "${OPTARG}" in
                servers=*)
                    SERVERS=${OPTARG##*=}
                    ;;
                conf_dir=*)
                    CONF_DIR=${OPTARG##*=}
                    ;;
                data_dir=*)
                    DATA_DIR=${OPTARG##*=}
                    ;;
                data_log_dir=*)
                    DATA_LOG_DIR=${OPTARG##*=}
                    ;;
                log_dir=*)
                    LOG_DIR=${OPTARG##*=}
                    ;;
                server_port=*)
                    SERVER_PORT=${OPTARG##*=}
                    ;;
                client_port=*)
                    CLIENT_PORT=${OPTARG##*=}
                    ;;
                leader_election_port=*)
                    LEADER_ELECTION_PORT=${OPTARG##*=}
                    ;;
                init_limit=*)
                    INIT_LIMIT=${OPTARG##*=}
                    ;;
                tick_time=*)
                    TICK_TIME=${OPTARG##*=}
                    ;;
                sync_limit=*)
                    SYNC_LIMIT=${OPTARG##*=}
                    ;;
                heap=*)
                    HEAP=${OPTARG##*=}
                    ;;
                max_client_cnxns=*)
                    MAX_CLIENT_CNXNS=${OPTARG##*=}
                    ;;
                snap_retain_count=*)
                    SNAP_RETAIN_COUNT=${OPTARG##*=}
                    ;;
                purge_interval=*)
                    PURGE_INTERVAL=${OPTARG##*=}
                    ;;
                max_session_timeout=*)
                    MAX_SESSION_TIMEOUT=${OPTARG##*=}
                    ;;
                min_session_timeout=*)
                    MIN_SESSION_TIMEOUT=${OPTARG##*=}
                    ;;
                log_level=*)
                    LOG_LEVEL=${OPTARG##*=}
                    ;;
                *)
                    echo "Unknown option --${OPTARG}" >&2
                    exit 1
                    ;;
            esac;;
        h)
            usage
            exit
            ;;
        v)
            echo "Parsing option: '-${optchar}'" >&2
            ;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            ;;
    esac
done

MIN_SESSION_TIMEOUT=${MIN_SESSION_TIMEOUT:- $((TICK_TIME*2))}
MAX_SESSION_TIMEOUT=${MAX_SESSION_TIMEOUT:- $((TICK_TIME*20))}
MYID_FILE="$DATA_DIR/myid"
CONFIG_FILE="$CONF_DIR/zoo.cfg"
LOGGER_PROPS_FILE="$CONF_DIR/log4j.properties"
JAVA_ENV_FILE="$CONF_DIR/java.env"
if [[ $HOST =~ (.*)-([0-9]+)$ ]]; then
    NAME=${BASH_REMATCH[1]}
    ORD=${BASH_REMATCH[2]}
else
    echo "Fialed to parse name and ordinal of Pod"
    exit 1
fi

MY_ID=$((ORD+1))

create_config && create_jvm_props && create_log_props && create_data_dirs && start